//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UseService140917.PersonService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonDTO", Namespace="http://schemas.datacontract.org/2004/07/WebServicePostPerson")]
    [System.SerializableAttribute()]
    public partial class PersonDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistriktField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EfternavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FornavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonnrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PostnrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TlfnrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresse {
            get {
                return this.AdresseField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresseField, value) != true)) {
                    this.AdresseField = value;
                    this.RaisePropertyChanged("Adresse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrikt {
            get {
                return this.DistriktField;
            }
            set {
                if ((object.ReferenceEquals(this.DistriktField, value) != true)) {
                    this.DistriktField = value;
                    this.RaisePropertyChanged("Distrikt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Efternavn {
            get {
                return this.EfternavnField;
            }
            set {
                if ((object.ReferenceEquals(this.EfternavnField, value) != true)) {
                    this.EfternavnField = value;
                    this.RaisePropertyChanged("Efternavn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fornavn {
            get {
                return this.FornavnField;
            }
            set {
                if ((object.ReferenceEquals(this.FornavnField, value) != true)) {
                    this.FornavnField = value;
                    this.RaisePropertyChanged("Fornavn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Personnr {
            get {
                return this.PersonnrField;
            }
            set {
                if ((this.PersonnrField.Equals(value) != true)) {
                    this.PersonnrField = value;
                    this.RaisePropertyChanged("Personnr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Postnr {
            get {
                return this.PostnrField;
            }
            set {
                if ((this.PostnrField.Equals(value) != true)) {
                    this.PostnrField = value;
                    this.RaisePropertyChanged("Postnr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tlfnr {
            get {
                return this.TlfnrField;
            }
            set {
                if ((object.ReferenceEquals(this.TlfnrField, value) != true)) {
                    this.TlfnrField = value;
                    this.RaisePropertyChanged("Tlfnr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Version {
            get {
                return this.VersionField;
            }
            set {
                if ((this.VersionField.Equals(value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PersonService.IPersonWcfService")]
    public interface IPersonWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonWcfService/GetAllePersoner", ReplyAction="http://tempuri.org/IPersonWcfService/GetAllePersonerResponse")]
        UseService140917.PersonService.PersonDTO[] GetAllePersoner();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPersonWcfService/GetAllePersoner", ReplyAction="http://tempuri.org/IPersonWcfService/GetAllePersonerResponse")]
        System.IAsyncResult BeginGetAllePersoner(System.AsyncCallback callback, object asyncState);
        
        UseService140917.PersonService.PersonDTO[] EndGetAllePersoner(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonWcfService/GetAllePersonerMedNavn", ReplyAction="http://tempuri.org/IPersonWcfService/GetAllePersonerMedNavnResponse")]
        UseService140917.PersonService.PersonDTO[] GetAllePersonerMedNavn(string fornavn, string efternavn, bool orderEfternavnFornavn);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPersonWcfService/GetAllePersonerMedNavn", ReplyAction="http://tempuri.org/IPersonWcfService/GetAllePersonerMedNavnResponse")]
        System.IAsyncResult BeginGetAllePersonerMedNavn(string fornavn, string efternavn, bool orderEfternavnFornavn, System.AsyncCallback callback, object asyncState);
        
        UseService140917.PersonService.PersonDTO[] EndGetAllePersonerMedNavn(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonWcfService/GetAllePersonerMedPostnr", ReplyAction="http://tempuri.org/IPersonWcfService/GetAllePersonerMedPostnrResponse")]
        UseService140917.PersonService.PersonDTO[] GetAllePersonerMedPostnr(int fraPostnr, int tilPostnr, bool orderEfternavnFornavn);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPersonWcfService/GetAllePersonerMedPostnr", ReplyAction="http://tempuri.org/IPersonWcfService/GetAllePersonerMedPostnrResponse")]
        System.IAsyncResult BeginGetAllePersonerMedPostnr(int fraPostnr, int tilPostnr, bool orderEfternavnFornavn, System.AsyncCallback callback, object asyncState);
        
        UseService140917.PersonService.PersonDTO[] EndGetAllePersonerMedPostnr(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonWcfService/GetPersonMedPersonnr", ReplyAction="http://tempuri.org/IPersonWcfService/GetPersonMedPersonnrResponse")]
        UseService140917.PersonService.PersonDTO GetPersonMedPersonnr(int personnr);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPersonWcfService/GetPersonMedPersonnr", ReplyAction="http://tempuri.org/IPersonWcfService/GetPersonMedPersonnrResponse")]
        System.IAsyncResult BeginGetPersonMedPersonnr(int personnr, System.AsyncCallback callback, object asyncState);
        
        UseService140917.PersonService.PersonDTO EndGetPersonMedPersonnr(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonWcfService/RetPersonData", ReplyAction="http://tempuri.org/IPersonWcfService/RetPersonDataResponse")]
        bool RetPersonData(UseService140917.PersonService.PersonDTO person);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPersonWcfService/RetPersonData", ReplyAction="http://tempuri.org/IPersonWcfService/RetPersonDataResponse")]
        System.IAsyncResult BeginRetPersonData(UseService140917.PersonService.PersonDTO person, System.AsyncCallback callback, object asyncState);
        
        bool EndRetPersonData(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonWcfServiceChannel : UseService140917.PersonService.IPersonWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllePersonerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllePersonerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public UseService140917.PersonService.PersonDTO[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((UseService140917.PersonService.PersonDTO[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllePersonerMedNavnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllePersonerMedNavnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public UseService140917.PersonService.PersonDTO[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((UseService140917.PersonService.PersonDTO[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllePersonerMedPostnrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllePersonerMedPostnrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public UseService140917.PersonService.PersonDTO[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((UseService140917.PersonService.PersonDTO[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPersonMedPersonnrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPersonMedPersonnrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public UseService140917.PersonService.PersonDTO Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((UseService140917.PersonService.PersonDTO)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetPersonDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RetPersonDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonWcfServiceClient : System.ServiceModel.ClientBase<UseService140917.PersonService.IPersonWcfService>, UseService140917.PersonService.IPersonWcfService {
        
        private BeginOperationDelegate onBeginGetAllePersonerDelegate;
        
        private EndOperationDelegate onEndGetAllePersonerDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllePersonerCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllePersonerMedNavnDelegate;
        
        private EndOperationDelegate onEndGetAllePersonerMedNavnDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllePersonerMedNavnCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllePersonerMedPostnrDelegate;
        
        private EndOperationDelegate onEndGetAllePersonerMedPostnrDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllePersonerMedPostnrCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPersonMedPersonnrDelegate;
        
        private EndOperationDelegate onEndGetPersonMedPersonnrDelegate;
        
        private System.Threading.SendOrPostCallback onGetPersonMedPersonnrCompletedDelegate;
        
        private BeginOperationDelegate onBeginRetPersonDataDelegate;
        
        private EndOperationDelegate onEndRetPersonDataDelegate;
        
        private System.Threading.SendOrPostCallback onRetPersonDataCompletedDelegate;
        
        public PersonWcfServiceClient() {
        }
        
        public PersonWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetAllePersonerCompletedEventArgs> GetAllePersonerCompleted;
        
        public event System.EventHandler<GetAllePersonerMedNavnCompletedEventArgs> GetAllePersonerMedNavnCompleted;
        
        public event System.EventHandler<GetAllePersonerMedPostnrCompletedEventArgs> GetAllePersonerMedPostnrCompleted;
        
        public event System.EventHandler<GetPersonMedPersonnrCompletedEventArgs> GetPersonMedPersonnrCompleted;
        
        public event System.EventHandler<RetPersonDataCompletedEventArgs> RetPersonDataCompleted;
        
        public UseService140917.PersonService.PersonDTO[] GetAllePersoner() {
            return base.Channel.GetAllePersoner();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAllePersoner(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllePersoner(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public UseService140917.PersonService.PersonDTO[] EndGetAllePersoner(System.IAsyncResult result) {
            return base.Channel.EndGetAllePersoner(result);
        }
        
        private System.IAsyncResult OnBeginGetAllePersoner(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetAllePersoner(callback, asyncState);
        }
        
        private object[] OnEndGetAllePersoner(System.IAsyncResult result) {
            UseService140917.PersonService.PersonDTO[] retVal = this.EndGetAllePersoner(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllePersonerCompleted(object state) {
            if ((this.GetAllePersonerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllePersonerCompleted(this, new GetAllePersonerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllePersonerAsync() {
            this.GetAllePersonerAsync(null);
        }
        
        public void GetAllePersonerAsync(object userState) {
            if ((this.onBeginGetAllePersonerDelegate == null)) {
                this.onBeginGetAllePersonerDelegate = new BeginOperationDelegate(this.OnBeginGetAllePersoner);
            }
            if ((this.onEndGetAllePersonerDelegate == null)) {
                this.onEndGetAllePersonerDelegate = new EndOperationDelegate(this.OnEndGetAllePersoner);
            }
            if ((this.onGetAllePersonerCompletedDelegate == null)) {
                this.onGetAllePersonerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllePersonerCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllePersonerDelegate, null, this.onEndGetAllePersonerDelegate, this.onGetAllePersonerCompletedDelegate, userState);
        }
        
        public UseService140917.PersonService.PersonDTO[] GetAllePersonerMedNavn(string fornavn, string efternavn, bool orderEfternavnFornavn) {
            return base.Channel.GetAllePersonerMedNavn(fornavn, efternavn, orderEfternavnFornavn);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAllePersonerMedNavn(string fornavn, string efternavn, bool orderEfternavnFornavn, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllePersonerMedNavn(fornavn, efternavn, orderEfternavnFornavn, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public UseService140917.PersonService.PersonDTO[] EndGetAllePersonerMedNavn(System.IAsyncResult result) {
            return base.Channel.EndGetAllePersonerMedNavn(result);
        }
        
        private System.IAsyncResult OnBeginGetAllePersonerMedNavn(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string fornavn = ((string)(inValues[0]));
            string efternavn = ((string)(inValues[1]));
            bool orderEfternavnFornavn = ((bool)(inValues[2]));
            return this.BeginGetAllePersonerMedNavn(fornavn, efternavn, orderEfternavnFornavn, callback, asyncState);
        }
        
        private object[] OnEndGetAllePersonerMedNavn(System.IAsyncResult result) {
            UseService140917.PersonService.PersonDTO[] retVal = this.EndGetAllePersonerMedNavn(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllePersonerMedNavnCompleted(object state) {
            if ((this.GetAllePersonerMedNavnCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllePersonerMedNavnCompleted(this, new GetAllePersonerMedNavnCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllePersonerMedNavnAsync(string fornavn, string efternavn, bool orderEfternavnFornavn) {
            this.GetAllePersonerMedNavnAsync(fornavn, efternavn, orderEfternavnFornavn, null);
        }
        
        public void GetAllePersonerMedNavnAsync(string fornavn, string efternavn, bool orderEfternavnFornavn, object userState) {
            if ((this.onBeginGetAllePersonerMedNavnDelegate == null)) {
                this.onBeginGetAllePersonerMedNavnDelegate = new BeginOperationDelegate(this.OnBeginGetAllePersonerMedNavn);
            }
            if ((this.onEndGetAllePersonerMedNavnDelegate == null)) {
                this.onEndGetAllePersonerMedNavnDelegate = new EndOperationDelegate(this.OnEndGetAllePersonerMedNavn);
            }
            if ((this.onGetAllePersonerMedNavnCompletedDelegate == null)) {
                this.onGetAllePersonerMedNavnCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllePersonerMedNavnCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllePersonerMedNavnDelegate, new object[] {
                        fornavn,
                        efternavn,
                        orderEfternavnFornavn}, this.onEndGetAllePersonerMedNavnDelegate, this.onGetAllePersonerMedNavnCompletedDelegate, userState);
        }
        
        public UseService140917.PersonService.PersonDTO[] GetAllePersonerMedPostnr(int fraPostnr, int tilPostnr, bool orderEfternavnFornavn) {
            return base.Channel.GetAllePersonerMedPostnr(fraPostnr, tilPostnr, orderEfternavnFornavn);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAllePersonerMedPostnr(int fraPostnr, int tilPostnr, bool orderEfternavnFornavn, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllePersonerMedPostnr(fraPostnr, tilPostnr, orderEfternavnFornavn, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public UseService140917.PersonService.PersonDTO[] EndGetAllePersonerMedPostnr(System.IAsyncResult result) {
            return base.Channel.EndGetAllePersonerMedPostnr(result);
        }
        
        private System.IAsyncResult OnBeginGetAllePersonerMedPostnr(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int fraPostnr = ((int)(inValues[0]));
            int tilPostnr = ((int)(inValues[1]));
            bool orderEfternavnFornavn = ((bool)(inValues[2]));
            return this.BeginGetAllePersonerMedPostnr(fraPostnr, tilPostnr, orderEfternavnFornavn, callback, asyncState);
        }
        
        private object[] OnEndGetAllePersonerMedPostnr(System.IAsyncResult result) {
            UseService140917.PersonService.PersonDTO[] retVal = this.EndGetAllePersonerMedPostnr(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllePersonerMedPostnrCompleted(object state) {
            if ((this.GetAllePersonerMedPostnrCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllePersonerMedPostnrCompleted(this, new GetAllePersonerMedPostnrCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllePersonerMedPostnrAsync(int fraPostnr, int tilPostnr, bool orderEfternavnFornavn) {
            this.GetAllePersonerMedPostnrAsync(fraPostnr, tilPostnr, orderEfternavnFornavn, null);
        }
        
        public void GetAllePersonerMedPostnrAsync(int fraPostnr, int tilPostnr, bool orderEfternavnFornavn, object userState) {
            if ((this.onBeginGetAllePersonerMedPostnrDelegate == null)) {
                this.onBeginGetAllePersonerMedPostnrDelegate = new BeginOperationDelegate(this.OnBeginGetAllePersonerMedPostnr);
            }
            if ((this.onEndGetAllePersonerMedPostnrDelegate == null)) {
                this.onEndGetAllePersonerMedPostnrDelegate = new EndOperationDelegate(this.OnEndGetAllePersonerMedPostnr);
            }
            if ((this.onGetAllePersonerMedPostnrCompletedDelegate == null)) {
                this.onGetAllePersonerMedPostnrCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllePersonerMedPostnrCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllePersonerMedPostnrDelegate, new object[] {
                        fraPostnr,
                        tilPostnr,
                        orderEfternavnFornavn}, this.onEndGetAllePersonerMedPostnrDelegate, this.onGetAllePersonerMedPostnrCompletedDelegate, userState);
        }
        
        public UseService140917.PersonService.PersonDTO GetPersonMedPersonnr(int personnr) {
            return base.Channel.GetPersonMedPersonnr(personnr);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetPersonMedPersonnr(int personnr, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPersonMedPersonnr(personnr, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public UseService140917.PersonService.PersonDTO EndGetPersonMedPersonnr(System.IAsyncResult result) {
            return base.Channel.EndGetPersonMedPersonnr(result);
        }
        
        private System.IAsyncResult OnBeginGetPersonMedPersonnr(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int personnr = ((int)(inValues[0]));
            return this.BeginGetPersonMedPersonnr(personnr, callback, asyncState);
        }
        
        private object[] OnEndGetPersonMedPersonnr(System.IAsyncResult result) {
            UseService140917.PersonService.PersonDTO retVal = this.EndGetPersonMedPersonnr(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPersonMedPersonnrCompleted(object state) {
            if ((this.GetPersonMedPersonnrCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPersonMedPersonnrCompleted(this, new GetPersonMedPersonnrCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPersonMedPersonnrAsync(int personnr) {
            this.GetPersonMedPersonnrAsync(personnr, null);
        }
        
        public void GetPersonMedPersonnrAsync(int personnr, object userState) {
            if ((this.onBeginGetPersonMedPersonnrDelegate == null)) {
                this.onBeginGetPersonMedPersonnrDelegate = new BeginOperationDelegate(this.OnBeginGetPersonMedPersonnr);
            }
            if ((this.onEndGetPersonMedPersonnrDelegate == null)) {
                this.onEndGetPersonMedPersonnrDelegate = new EndOperationDelegate(this.OnEndGetPersonMedPersonnr);
            }
            if ((this.onGetPersonMedPersonnrCompletedDelegate == null)) {
                this.onGetPersonMedPersonnrCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPersonMedPersonnrCompleted);
            }
            base.InvokeAsync(this.onBeginGetPersonMedPersonnrDelegate, new object[] {
                        personnr}, this.onEndGetPersonMedPersonnrDelegate, this.onGetPersonMedPersonnrCompletedDelegate, userState);
        }
        
        public bool RetPersonData(UseService140917.PersonService.PersonDTO person) {
            return base.Channel.RetPersonData(person);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginRetPersonData(UseService140917.PersonService.PersonDTO person, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRetPersonData(person, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndRetPersonData(System.IAsyncResult result) {
            return base.Channel.EndRetPersonData(result);
        }
        
        private System.IAsyncResult OnBeginRetPersonData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            UseService140917.PersonService.PersonDTO person = ((UseService140917.PersonService.PersonDTO)(inValues[0]));
            return this.BeginRetPersonData(person, callback, asyncState);
        }
        
        private object[] OnEndRetPersonData(System.IAsyncResult result) {
            bool retVal = this.EndRetPersonData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRetPersonDataCompleted(object state) {
            if ((this.RetPersonDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RetPersonDataCompleted(this, new RetPersonDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RetPersonDataAsync(UseService140917.PersonService.PersonDTO person) {
            this.RetPersonDataAsync(person, null);
        }
        
        public void RetPersonDataAsync(UseService140917.PersonService.PersonDTO person, object userState) {
            if ((this.onBeginRetPersonDataDelegate == null)) {
                this.onBeginRetPersonDataDelegate = new BeginOperationDelegate(this.OnBeginRetPersonData);
            }
            if ((this.onEndRetPersonDataDelegate == null)) {
                this.onEndRetPersonDataDelegate = new EndOperationDelegate(this.OnEndRetPersonData);
            }
            if ((this.onRetPersonDataCompletedDelegate == null)) {
                this.onRetPersonDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRetPersonDataCompleted);
            }
            base.InvokeAsync(this.onBeginRetPersonDataDelegate, new object[] {
                        person}, this.onEndRetPersonDataDelegate, this.onRetPersonDataCompletedDelegate, userState);
        }
    }
}
